name: PR Notification to Mattermost

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify-mattermost:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Status Message and Send Notification
        run: |

          STATUS=""
          COLOR=""

          case "${{ github.event.action }}" in
            "opened")
              STATUS=":manggom_1:  **새로운 PR이 생성되었습니다!** :manggom_1: "
              COLOR="#36a64f"
              ;;
            "reopened")
              STATUS=":duck_dance: **PR이 다시 열렸습니다!** :duck_dance: "
              COLOR="#ffcc00"
              ;;
            "closed")
              if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
                STATUS=":kirby_shake:  **PR이 머지되었습니다!** :kirby_shake: "
                COLOR="#0000ff"
              else
                STATUS=":sad-shin-chang:  **PR이 닫혔습니다.** :sad-shin-chang: "
                COLOR="#ff0000"
              fi
              ;;
          esac


          if [ -z "${{ secrets.MATTERMOST_WEBHOOK }}" ]; then
            echo "❌ Webhook URL이 설정되지 않았습니다."
            exit 1
          fi

          curl -X POST -H 'Content-Type: application/json' \
            -d @- ${{ secrets.MATTERMOST_WEBHOOK }} <<EOF
          {
            "attachments": [{
              "color": "$COLOR",
              "title": "$STATUS",
              "text": "📌 *제목:*  **${{ github.event.pull_request.title }}**  \n\n👤 *작성자:*  **${{ github.event.pull_request.user.login }}**  \n\n🔗 [PR 링크](${{ github.event.pull_request.html_url }})",
              "footer": "😺 Approve 필수! 😺 ",
              "ts": $(date +%s)
            }]
          }
          EOF


